version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          keys:
            - $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
            - $CACHE_VERSION-dependencies-
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          paths:
            - node_modules
          key: $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
  lint:
    docker:
      - image: circleci/node:dubnium
    steps:
      - run : yarn lint && yarn format:checkout
  test:
    docker:
      - image: circleci/node:dubnium
    steps:
      - run : yarn test:ci
      
workflows:
  version: 2
  build_lint_test:
    jobs:
      - build
      - lint
          requires:
            - build
      - test
          requires:
            - build