version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
  lint:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn lint && yarn format:check
  test_bdd:
    docker:
      - image: circleci/node:dubnium
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: psqluser
          POSTGRES_PASSWORD: psqlpassword
          POSTGRES_DB: psdb
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          command: yarn test:e2e
          environment:
            DATABASE_URL: postgres://psqluser:psqlpassword@localhost:5432/psdb
            JWT_SECRET: 'test'
            API_PORT: 3000
            API_HOST: localhost
            API_PROTOCOL: http
  test_ci:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn test:ci
  doc_build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ .Environment.CACHE_VERSION }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run: yarn run doc:build
  docker_build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t acroquelois/my-awesome-ci-expr:$CIRCLE_BUILD_NUM .
      - run: docker push acroquelois/my-awesome-ci-expr:$CIRCLE_BUILD_NUM
workflows:
  version: 2
  build_circleci:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test_bdd:
          requires:
            - build
      - test_ci:
          requires:
            - build
      - docker_build:
          requires:
            - test_ci
            - lint
            - test_bdd
      - doc_build:
          requires:
            - test_ci
            - lint
            - test_bdd
