version: 2
jobs:
  install:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - restore_cache:
          keys:
            - $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
            - $CACHE_VERSION-dependencies-
      - run: yarn global add node-gyp && yarn install
      - save_cache:
          paths:
            - node_modules
          key: $CACHE_VERSION-dependencies-{{ checksum "package.json" }}
  lint:
    steps:
      - run : yarn lint && yarn format:checkout
  test:
    steps:
      - run : yarn test:ci
